add more tests

diff --git a/skustomize b/skustomize
--- a/skustomize
+++ b/skustomize
@@ -21,9 +21,9 @@ get_kust_bin() {
 check_deps() {
   local missed=0
   local -A deps=([yq]=https://github.com/mikefarah/yq [vals]=https://github.com/helmfile/vals)
-  for bin in yq vals; do
-    if ! which $bin &>/dev/null; then
-      echo -e "\033[1;31m[ERROR]: $bin is required, download from ${deps[$bin]}/releases\033[0m"
+  for dep in yq vals; do
+    if ! which "${dep}" &>/dev/null; then
+      echo -e "\033[1;31m[ERROR]: ${dep} is required, download from ${deps[$dep]}/releases\033[0m"
       ((missed += 1))
     fi
   done
@@ -84,13 +84,13 @@ VALS_REF_REGEX='((secret)?ref)\+([^\+:]*:\/\/[^\+\n "]+)\+?'
 
 check_vals_ref_uri() {
   local count=0
-  for type in files literals; do
+  for entry in files literals; do
     while read -r line; do
       if [[ "$line" =~ ^=?$VALS_REF_REGEX ]]; then
-        echo -e "\033[1;31m[ERROR]: invalid $type source: [$line], expected key=value \033[0m"
+        echo -e "\033[1;31m[ERROR]: invalid $entry source: [$line], expected key=value \033[0m"
         ((count += 1))
       fi
-    done < <(TYPE="$type" yq '.secretGenerator[][strenv(TYPE)][]' "${KUST_FILES[0]}")
+    done < <(ENTRY="$entry" yq '.secretGenerator[][strenv(ENTRY)][]' "${KUST_FILES[0]}")
   done
   [ $count -eq 0 ]
 }
