support kubectl (#4)
* support kubectl

diff --git a/skustomize b/skustomize
--- a/skustomize
+++ b/skustomize
@@ -4,21 +4,46 @@ set -eu
 set -o pipefail
 
 : "${KUSTOMIZE_BIN:=kustomize}"
-
+: "${KUBECTL_BIN:=kubectl}"
+USE_KUBECTL=false
 WORKDIR=.
 SUB_COMMAND=""
 BOOL_FLAG=true
 SHOW_HELP=false
 declare -a GLOBAL_FLAGS=() SUB_FLAGS=() KUST_FILES=() KUST_DIRS=()
-
 CMDS="(build|cfg|completion|create|edit|fn|help|localize|version|docs-fn|docs-fn-spec|docs-io-annotations|docs-merge|docs-merge3|tutorials-command-basics|tutorials-function-basics)"
+
+get_kust_bin() {
+  if ! which "${KUSTOMIZE_BIN}" &>/dev/null; then
+    if ! which "${KUBECTL_BIN}" &>/dev/null; then
+      echo -e "\033[1;31m[ERROR]: can't find ${KUSTOMIZE_BIN} or ${KUBECTL_BIN} installed\033[0m"
+      exit 1
+    fi
+    # if use kubectl
+    KUSTOMIZE_BIN="${KUBECTL_BIN}"
+    USE_KUBECTL=true
+    SUB_COMMAND=build
+  fi
+}
+
+check_deps() {
+  local missed=0
+  local -A deps=([yq]=https://github.com/mikefarah/yq [vals]=https://github.com/helmfile/vals)
+  for dep in yq vals; do
+    if ! which "${dep}" &>/dev/null; then
+      echo -e "\033[1;31m[ERROR]: ${dep} is required, download from ${deps[$dep]}/releases\033[0m"
+      ((missed += 1))
+    fi
+  done
+  [ $missed -eq 0 ]
+}
 
 parse_flags() {
   for flag in "$@"; do
     if [ "$flag" == "-h" ] || [ "$flag" == "--help" ]; then
       SHOW_HELP=true
     fi
-    if [[ $flag =~ ^$CMDS$ ]]; then
+    if [ -z "$SUB_COMMAND" ] && [[ $flag =~ ^$CMDS$ ]]; then
       SUB_COMMAND="$flag"
     elif [ -z "$SUB_COMMAND" ] || [ "$flag" == "--stack-trace" ]; then
       GLOBAL_FLAGS+=("$flag")
@@ -60,13 +85,13 @@ VALS_REF_REGEX='((secret)?ref)\+([^\+:]*:\/\/[^\+\n "]+)\+?'
 
 check_vals_ref_uri() {
   local count=0
-  for type in files literals; do
+  for entry in files literals; do
     while read -r line; do
       if [[ "$line" =~ ^=?$VALS_REF_REGEX ]]; then
-        echo -e "\033[1;31m[ERROR]: invalid $type source: [$line], expected key=value \033[0m"
+        echo -e "\033[1;31m[ERROR]: invalid $entry source: [$line], expected key=value \033[0m"
         ((count += 1))
       fi
-    done < <(TYPE="$type" yq '.secretGenerator[][strenv(TYPE)][]' "${KUST_FILES[0]}")
+    done < <(ENTRY="$entry" yq '.secretGenerator[][strenv(ENTRY)][]' "${KUST_FILES[0]}")
   done
   [ $count -eq 0 ]
 }
@@ -110,7 +135,15 @@ build_wrapper() {
 
 # shellcheck disable=SC2091
 if ! $(return 0 2>/dev/null); then
+  get_kust_bin
+  check_deps
   parse_flags "$@"
+
+  # if install as kubectl plugin
+  if [ "$USE_KUBECTL" == true ]; then
+    set -- kustomize "${SUB_FLAGS[@]}"
+  fi
+
   if [ "${#KUST_DIRS[@]}" -lt 2 ] && [ "$SUB_COMMAND" == build ] && [ "$SHOW_HELP" == false ]; then
     build_wrapper "$@"
   fi
